2017-04-16 17:29:48.959 [error] <0.3378.0>@lasp_workflow:init:92 Error connecting to redis for workflow management: {error,{connection_error,{connection_error,econnrefused}}}
2017-04-16 17:29:48.959 [error] <0.3378.0> CRASH REPORT Process <0.3378.0> with 1 neighbours exited with reason: {error,{connection_error,{connection_error,econnrefused}}} in gen_server:init_it/6 line 344
2017-04-16 17:29:48.959 [error] <0.3307.0> Supervisor lasp_sup had child lasp_workflow started with lasp_workflow:start_link() at undefined exit with reason {error,{connection_error,{connection_error,econnrefused}}} in context start_error
2017-04-16 17:29:48.959 [error] <0.3305.0> CRASH REPORT Process <0.3305.0> with 0 neighbours exited with reason: {{shutdown,{failed_to_start_child,lasp_workflow,{error,{connection_error,{connection_error,econnrefused}}}}},{lasp_app,start,[normal,[]]}} in application_master:init/4 line 134
